### ISSUE TITLE
Improvements.

### ISSUE THREAD

**Issue by krmgns** [1sahinomer1/weatherApp#1]
Problems:
1. Input event `onChange` should be changed to `onInput`, so quickly writing "Hatay" returns "Hātā" city results.
2. Checking only `200` code from response is not enough, it would better having a proper error handle. Otherwise `{Math.round(weatherData.main.temp)}` could causes unexpected errors, also `{Math.round(weatherData?.main.temp)}` will yield a `NaN` result.
3. Type is missing for `useState()` statement of `cityName`, it could be done like `useState<string>("")`.

Sources: 
- https://github.com/1sahinomer1/weatherApp/blob/master/src/App.tsx#L39 (1)
- https://github.com/1sahinomer1/weatherApp/blob/master/src/App.tsx#L60 (1)
- https://github.com/1sahinomer1/weatherApp/blob/master/src/App.tsx#L32 (2)
- https://github.com/1sahinomer1/weatherApp/blob/master/src/App.tsx#L11 (3)

**Comment by 1sahinomer1** [comment]
Thanks for the feedback. Problems is corrected.

**Comment by krmgns** [comment]
@1sahinomer1 

Problem 1: I think it could be done like: `{weatherData && (...` => `{weatherData ? (...) : No result found!`. So in this way these statements could be changed as: `{weatherData?.name} => {weatherData.name}` and `{weatherData?.sys.country} => {weatherData.sys.country}`
Source: https://github.com/1sahinomer1/weatherApp/blob/master/src/App.tsx#L67

**Comment by 1sahinomer1** [comment]
I want it to stay like this because it is only input on the first screen , like `{weatherData && (...`. But i changed `{weatherData?.name} => {weatherData.name}`
